### PR TITLE
Upgrade package for use with ST 4132+

### PR DESCRIPTION
**Pull request by deathaxe**
This PR suggests a major upgrade to

1. use latest features and base syntaxes of ST 4132.
2. upgrade liquid language features
3. fully support Jekyll syntax tags

Note: This PR requires a change to package_control_channel to limit this changes to ST4132+

Suggestion: Interested in moving the package to SublimeText organization?

### CODE REVIEW

**Comment by deathaxe** [comment]
@braver: Any thoughts?

**Comment by braver** [comment]
Sorry for not responding. Apparently my GitHub account kinda broke and was unable to send me notifications by e-mail, and effectively also unable to notify me about the problem. I was wondering why everything was so quiet 😆 

> Suggestion: Interested in moving the package to SublimeText organization?

Yes, definitely. Shall I just initiate the move? I haven't used this languages in ages and have no immediate interest in maintaining it all by myself.

**Comment by braver** [comment]
Alright, it's all yours. Hit me with a PR over at [package_control_channel](https://github.com/wbond/package_control_channel/pulls) when you're ready.

**Comment by deathaxe** [comment]
Something seems wrong with your invitation link. Can't accept it.

Basically I am done. Just reorganized work into `develop` branch to keep `master` clean. Also created a st4126 branch on my end with a backported Markdown syntax, so we can provide all features for latest stable release as well.

As you are already a maintainer of SublimeText organization you should probably be able to move the package and rename it to "Liquid" afterwards. If an admin is required we might ask @FichteFoll to help us out - maybe at least with adding me as contributor/maintainer.

I'd update package control registry to use new location then.

**Comment by FichteFoll** [comment]
I have renamed the repository and configured permissions for @braver and @deathaxe.

**Comment by braver** [comment]
> Something seems wrong with your invitation link. Can't accept it.

Yeah, that wasn't necessary. I couldn't find the transfer button and also assumed I couldn't do the transfer myself. But I found out I could and it has already been done. Sorry about the confusion, I'm rusty...

**Comment by FichteFoll** [comment]
As an aside, you may want to include a license.

**Comment by braver** [comment]
> As an aside, you may want to include a license.

done

(by the way, none of the original work of the original repo the fork was based on remains here, I fully rewrote it years ago, but yeah ... I'm not particular about the license stuff 🤷🏻 )

**Pull request merged**
